### PR TITLE
Lybercore base

### PR DESCRIPTION
**Pull request by atz**
Resque doesn't care about any of these changes because all it ever calls is `MyBotClass.perform(...)`.  So it has no concept of any instantiation happening. From Resque's perspective, everything happens behind a class method, as they document here:
    https://github.com/resque/resque#overview

### CODE REVIEW

**Comment by ndushay** [comment]
I would like to hold off on this at least until I get robots running in prod.

**Comment by ndushay** [comment]
I don't want to merge this to master until it is tested on stage.

**Comment by atz** [comment]
@ndushay is that something anyone can do or do you have secret sauce tests that must be done manually?

**Comment by atz** [comment]
Note: `argo-stage` is currently inaccessible due to authentication migration issues.  I have not heard any projection for its being restored to use.

**Comment by atz** [comment]
argo-stage is back up so this is testable

**Pull request closed without merging**
