### PR TITLE
Added missing requires.

### LINKED ISSUE #134: NameError in rake preservation_logs
See https://app.honeybadger.io/projects/55564/faults/47040619

### PR DESCRIPTION
**Pull request by justinlittman**
closes #134

### CODE REVIEW

**Comment by justinlittman** [comment]
Any tests on rake task execution that you can point me to @jcoyne?

**Comment by jcoyne** [comment]
@justinlittman is that necessary?  Can a test be added that covers this line? https://coveralls.io/builds/23311898/source?filename=lib/activity_reporter.rb#L34

**Comment by justinlittman** [comment]
@jcoyne If you test via rspec the error doesn't occur. I suspect the file must be required somewhere in the test scaffolding. Other suggestions? I could invoke the rake task as a system command?

**Comment by justinlittman** [comment]
Closing in favor of https://github.com/sul-dlss/preservation_robots/pull/136

**Pull request closed without merging**
